### PR TITLE
Upgrade TargetPlatformMinVersion for WinUI2.8

### PR DESCRIPTION
**Pull request by chiaramooney**
The current TargetPlatformMinVersion for the module is not compatible with WinUI2.8. Since this module is in RNW core, we must upgrade react-native-xaml in order for CI to succeed. 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/react-native-xaml/pull/213)

### CODE REVIEW

**Comment by asklar** [comment]
this is an unexpected change... I didn't realize WinUI 2.8 has a higher min platform requirement. 
For RNW we say our current min platform requirement is 16299: https://microsoft.github.io/react-native-windows/docs/rnw-dependencies
Can you investigate why 2.8 raises the min platform requirement?

**Comment by chiaramooney** [comment]
> this is an unexpected change... I didn't realize WinUI 2.8 has a higher min platform requirement. For RNW we say our current min platform requirement is 16299: https://microsoft.github.io/react-native-windows/docs/rnw-dependencies Can you investigate why 2.8 raises the min platform requirement?

Yep I can investigate. In my RNW PR WinUI 2.8 is also asking me to bump the TargetPlatformMinVersion.

**Comment by chiaramooney** [comment]
@asklar Found this under What's new in the documentation. "The minimum supported version of WinUI 2 is now Windows 10, version 1809 - build 17763."

**Comment by asklar** [comment]
@chiaramooney can you start a thread to find out why? in parallel, we need to update the docs for RNW to reflect this, and also update the release notes for whichever release will have the 2.8 update

**Comment by asklar** [comment]
I still don't think this change is needed for react-native-xaml. It likely is necessary for RNW to set its min version higher, but react-native-xaml and other modules shouldn't need to update.

**Review by asklar — CHANGES_REQUESTED** [review]
I still don't think this change is needed for react-native-xaml. It likely is necessary for RNW to set its min version higher, but react-native-xaml and other modules shouldn't need to update.

**Comment by chiaramooney** [comment]
@asklar I have the PR going to update RNW to winUI2.8 here https://github.com/microsoft/react-native-windows/pull/10282. Looking at this build log here https://dev.azure.com/ms/react-native-windows/_build/results?buildId=334209&view=logs&jobId=7c3f23e2-00c8-53a7-e684-d87b686ee4fc&j=7c3f23e2-00c8-53a7-e684-d87b686ee4fc&t=d11de1e7-d5ec-526c-ce13-feef2e539b3f the react-native-xaml project is failing saying it needs to bump its targetminversion.

**Comment by chiaramooney** [comment]
Closing for now. Awaiting decision on move to 2.8.

**Pull request closed without merging**
